patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 207797165735.dkr.ecr.ap-northeast-2.amazonaws.com/frontend
  newName: 207797165735.dkr.ecr.ap-northeast-2.amazonaws.com/frontend
  newTag: 726543c2d27d0c4f5f17a86cce161ac51b90592b
